### ISSUE TITLE
Restore and enhance review functionality on Starter-Frontend 

### ISSUE THREAD

**Issue by fthobe** [solidusio-contrib/solidus_reviews#124]
Following issues are blocking the extension from functioning correctly: 

- [ ] #120 to restore on starter frontend
- [ ] #50 to build the whole functionality inside the starter front-end PDP

Following functionalities would be nice to have: 

- [ ] #63 allowing to sort for better reviews

**Comment by fthobe** [comment]
@tvdeyen @jarednorman 

Questions:
1. is cache counting and a table an acceptable way to count the thumbs up thumbs down actions? It is outlined in a guide in the edge documetation as a reference implementation to count likes
2. Do you have other preferences or no gos?

**Comment by fthobe** [comment]
Hey, 
this is the first draft for a new review extension. 
The extension currently works with the starter frontend and provides a simple review functionality. 
[https://github.com/gms-electronics/solidus_reviews/pull/2](https://github.com/gms-electronics/solidus_reviews/pull/2)

- [X] jquery free
- [X] jscript only 
- [X] works with starter frontend
- [X] works with admin backend
- [ ] thumbs up / down for reviews not implemented on frontend yet
- [ ] report review not implemented on fronte-end yet
- [ ] Style aligned with starter frontend
- [ ] filter for store not yet implemented
- [ ] circleci not fully implemented yet, ([shahmayur001](https://github.com/shahmayur001) could need your help there

@tvdeyen @jarednorman @kennyadsl

**Comment by kennyadsl** [comment]
👍 Code wise it looks ok to me overall. Still have to go into details but the direction seems fine. Do you need anything from us now to continue with this work?

**Comment by fthobe** [comment]
@kennyadsl we are struggling with these issues: 

1. In the Solidus Review gem, settings are stored in preferences, which reset if we restart the application. How do we generally handle this when we want any setting to be available in SolidusAdmin, persist after restarting the server, and save data properly? Do we hard code a configuration file or store settings in additional tables.
2. In the Solidus Review gem, test cases are built with the old, deprecated frontend. What is the correct way to build test cases or create a demo app for test cases using the new Starter Frontend? Please be as specific as any possible as @shahmayur001 did struggle to understand you.
3. What is the best way to deface the view part and view components? We want to add a few modifications to the Review gem that will affect the product or taxon pages. How should we handle these modifications?
4. What is the best way to implement JavaScript? Should we use Hotwire, Backbone.js, or plain JavaScript? There are different structures used in various parts of the application.
5. Sometimes, we encounter issues with receiving params in different formats, such as those from the Solidus API, backend, or core. In such situations, what is the best way to handle and normalize these parameters?

**Comment by kennyadsl** [comment]
1. Which settings are you talking about? Can you link a specific file/LOC? Is the application a real application or a sandbox environment? More details on the context where you are facing the issue might be useful.
2. the starter fronted is [copying frontend specs over the host application](https://github.com/solidusio/solidus_starter_frontend/blob/9f6d3974f9f088269a653296e5cd125363308063/template.rb#L148). We can do the same here in the extension installer.
3. Ideally, there is no need for deface and we should change the views of the starter frontend with the installer (like injecting a `render "reviews"` in an existing starter frontend view)
4. Do you mean for the admin or storefront? By the way, the Hotwire stack is the preferred way. 
5. Can you make a more specific example, not sure I follow here.

**Comment by fthobe** [comment]
All points are related to this gem:

> 1. Which settings are you talking about? Can you link a specific file/LOC? Is the application a real application or a sandbox environment? More details on the context where you are facing the issue might be useful.
> 
None of the admin settings of reviews seem to be stored anywhere but in memory, in fact don't seem to persist after a restart of the service. Is this by design (which means the interface is wrong) or incomplete implementation (which probably means we miss tables) or is there a 3rd way (like writing a conf as in eg Wordpress from a PHP script with appropriate elevated rights).
https://github.com/solidusio-contrib/solidus_reviews/blob/215ad0209b547bd7a2899fb87760dd5258184091/app/controllers/spree/admin/review_settings_controller.rb#L4

> 2. the starter fronted is [copying frontend specs over the host application](https://github.com/solidusio/solidus_starter_frontend/blob/9f6d3974f9f088269a653296e5cd125363308063/template.rb#L148). We can do the same here in the extension installer.
> 

@shahmayur001 , can you work with these instructions?

> 3. Ideally, there is no need for deface and we should change the views of the starter frontend with the installer (like injecting a `render "reviews"` in an existing starter frontend view)
> 
Ok, can you give an example of any extension doing doing that on the starter-frontend
> 4. Do you mean for the admin or storefront? By the way, the Hotwire stack is the preferred way. 
> 
Both, does Hotwire apply to admin as well as frontend?
> 5. Can you make a more specific example, not sure I follow here.
There you go: ![image](https://github.com/user-attachments/assets/69e83521-67f2-47b6-8324-0efab97303fe)

**Comment by shahmayur001** [comment]
@kennyadsl Thank you so much for your prompt response.

1) Adding more context: In the SolidusReview gem, we provide a few settings to the admin, but these are just preferences and reset when the application restarts, such as in the `ReviewsConfiguration` file. Is it possible to make these settings permanent instead of temporary?
2) Thank you! I will try this out and let you know.
3) Got it, thank you.
4) Got it, thank you.
5) A specific example is the `SolidusGiftCard` gem. As you can see in above screenshot, to work with the `GiftCard` parameters, I used different conditions as a workaround. However, I would like to understand how to properly tackle this kind of situation.

**Comment by fthobe** [comment]
@kennyadsl we seem to still struggle with point 2.
